var history_console = ""
+ "Slf4jLogger started<br>" 
+ "System started with N=3<br>" 
+ "main: Received other processes' info.<br>" 
+ "1: Received other processes' info.<br>" 
+ "2: Received other processes' info.<br>" 
+ "3: Received other processes' info.<br>" 
+ "2: Becoming faulty.<br>" 
+ "1: Launching. Starting sequential puts (followed by sequential gets).<br>" 
+ "3: Launching. Starting sequential puts (followed by sequential gets).<br>" 
+ "1: Starting put operation (curr_iter: 1, curr_op: 1, until: 6).<br>" 
+ "3: Starting put operation (curr_iter: 1, curr_op: 1, until: 6).<br>" 
+ "1: Sending write acknowledgement requests.<br>" 
+ "3: Sending write acknowledgement requests.<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 2, 1)> received from 1. Sending <WriteAck(1, 2, 0, 1)> to 1.<br>" 
+ "1: Acknowledge/write request <WriteAckReq(1, 2, 1)> received from 1. Sending <WriteAck(1, 2, 0, 1)> to 1.<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 1, 1)> received from 3. Sending <WriteAck(1, 1, 0, 1)> to 3.<br>" 
+ "1: Acknowledge/write request <WriteAckReq(1, 1, 1)> received from 3. Sending <WriteAck(1, 1, 0, 1)> to 3.<br>" 
+ "1: Acknowledge/put answer received from 3. Received <WriteAck(1, 2, 0, 1)><br>" 
+ "3: Acknowledge/put answer received from 3. Received <WriteAck(1, 1, 0, 1)><br>" 
+ "1: Acknowledge/put answer received from 1. Received <WriteAck(1, 2, 0, 1)><br>" 
+ "3: Acknowledge/put answer received from 1. Received <WriteAck(1, 1, 0, 1)><br>" 
+ "1: PUT : Got answers from a majority of actors. Continuing put operation <1, 2, 1>.<br>" 
+ "3: PUT : Got answers from a majority of actors. Continuing put operation <1, 1, 1>.<br>" 
+ "1: Got coherent maximum timestamp. Continuing put operation <1, 2, 1>.<br>" 
+ "1: Write operation <Write(1, 2, 1)> received from 1.<br>" 
+ "1: Write operation complete with <Write(1, 2, 1)>, sending <WriteFinished()> to 1.<br>" 
+ "1: Acknowledge/writeFinished answer <WriteFinished()> received from 1.<br>" 
+ "1: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "1: Put operation complete with (k = 1, v = 2); new timestamp: 1.<br>" 
+ "1: Starting get operation (curr_iter: 2, curr_op: 2, until: 6).<br>" 
+ "1: Sending read acknowledgement requests.<br>" 
+ "1: Acknowledge/get request received from 1 for key 1. Sending <ReadAck(1, 2, 1, 2)> to 1.<br>" 
+ "1: Acknowledge/get answer <ReadAck(1, 2, 1, 2)> received from 1.<br>" 
+ "3: Got coherent maximum timestamp. Continuing put operation <1, 1, 1>.<br>" 
+ "3: Write operation <Write(1, 2, 1)> received from 1.<br>" 
+ "3: Write operation complete with <Write(1, 2, 1)>, sending <WriteFinished()> to 1.<br>" 
+ "3: Acknowledge/get request received from 1 for key 1. Sending <ReadAck(1, 2, 1, 2)> to 1.<br>" 
+ "3: Write operation <Write(1, 1, 1)> received from 3.<br>" 
+ "3: Write operation complete with <Write(1, 1, 1)>, sending <WriteFinished()> to 3.<br>" 
+ "1: Write operation <Write(1, 1, 1)> received from 3.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "1: Write operation complete with <Write(1, 1, 1)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Put operation complete with (k = 1, v = 1); new timestamp: 1.<br>" 
+ "1: Acknowledge/get answer <ReadAck(1, 2, 1, 2)> received from 3.<br>" 
+ "1: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "1: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "1: Get operation complete. Returning <k, v, t : (1, 2, 1)>.<br>" 
+ "3: Starting get operation (curr_iter: 2, curr_op: 2, until: 6).<br>" 
+ "1: Write operation <Write(1, 2, 1)> received from 1.<br>" 
+ "3: Sending read acknowledgement requests.<br>" 
+ "1: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "1: Write operation complete with <Write(1, 2, 1)>, sending <WriteFinished()> to 1.<br>" 
+ "3: Write operation <Write(1, 2, 1)> received from 1.<br>" 
+ "1: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 1, 1, 2)> to 3.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "3: Write operation complete with <Write(1, 2, 1)>, sending <WriteFinished()> to 1.<br>" 
+ "1: Acknowledge/writeFinished answer <WriteFinished()> received from 1.<br>" 
+ "1: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 1, 1, 2)> to 3.<br>" 
+ "1: Get operation complete. Returning <k, v, t : (1, 1, 1)>.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 1, 1, 2)> received from 1.<br>" 
+ "1: Starting put operation (curr_iter: 3, curr_op: 3, until: 6).<br>" 
+ "1: Sending write acknowledgement requests.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 1, 1, 2)> received from 3.<br>" 
+ "3: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "1: Acknowledge/write request <WriteAckReq(1, 7, 3)> received from 1. Sending <WriteAck(1, 7, 1, 3)> to 1.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 1, 1)>.<br>" 
+ "1: Acknowledge/put answer received from 1. Received <WriteAck(1, 7, 1, 3)><br>" 
+ "1: Write operation <Write(1, 1, 1)> received from 3.<br>" 
+ "1: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "1: Write operation complete with <Write(1, 1, 1)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 7, 3)> received from 1. Sending <WriteAck(1, 7, 1, 3)> to 1.<br>" 
+ "3: Write operation <Write(1, 1, 1)> received from 3.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "1: Acknowledge/put answer received from 3. Received <WriteAck(1, 7, 1, 3)><br>" 
+ "3: Write operation complete with <Write(1, 1, 1)>, sending <WriteFinished()> to 3.<br>" 
+ "1: PUT : Got answers from a majority of actors. Continuing put operation <1, 7, 2>.<br>" 
+ "1: Got coherent maximum timestamp. Continuing put operation <1, 7, 2>.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 1.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 1, 1)>.<br>" 
+ "1: Write operation <Write(1, 7, 2)> received from 1.<br>" 
+ "3: Starting put operation (curr_iter: 3, curr_op: 3, until: 6).<br>" 
+ "1: Write operation complete with <Write(1, 7, 2)>, sending <WriteFinished()> to 1.<br>" 
+ "3: Sending write acknowledgement requests.<br>" 
+ "1: Acknowledge/writeFinished answer <WriteFinished()> received from 1.<br>" 
+ "1: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "1: Put operation complete with (k = 1, v = 7); new timestamp: 2.<br>" 
+ "1: Acknowledge/write request <WriteAckReq(1, 7, 3)> received from 3. Sending <WriteAck(1, 7, 2, 3)> to 3.<br>" 
+ "1: Starting get operation (curr_iter: 4, curr_op: 4, until: 6).<br>" 
+ "1: Sending read acknowledgement requests.<br>" 
+ "1: Acknowledge/get request received from 1 for key 1. Sending <ReadAck(1, 7, 2, 4)> to 1.<br>" 
+ "1: Acknowledge/get answer <ReadAck(1, 7, 2, 4)> received from 1.<br>" 
+ "3: Write operation <Write(1, 7, 2)> received from 1.<br>" 
+ "3: Write operation complete with <Write(1, 7, 2)>, sending <WriteFinished()> to 1.<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 7, 3)> received from 3. Sending <WriteAck(1, 7, 2, 3)> to 3.<br>" 
+ "3: Acknowledge/put answer received from 1. Received <WriteAck(1, 7, 2, 3)><br>" 
+ "3: Acknowledge/get request received from 1 for key 1. Sending <ReadAck(1, 7, 2, 4)> to 1.<br>" 
+ "1: Acknowledge/get answer <ReadAck(1, 7, 2, 4)> received from 3.<br>" 
+ "3: Acknowledge/put answer received from 3. Received <WriteAck(1, 7, 2, 3)><br>" 
+ "1: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: PUT : Got answers from a majority of actors. Continuing put operation <1, 7, 3>.<br>" 
+ "1: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "3: Got coherent maximum timestamp. Continuing put operation <1, 7, 3>.<br>" 
+ "1: Get operation complete. Returning <k, v, t : (1, 7, 2)>.<br>" 
+ "3: Write operation <Write(1, 7, 3)> received from 3.<br>" 
+ "1: Write operation <Write(1, 7, 3)> received from 3.<br>" 
+ "1: Write operation complete with <Write(1, 7, 3)>, sending <WriteFinished()> to 3.<br>" 
+ "1: Write operation <Write(1, 7, 2)> received from 1.<br>" 
+ "1: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "1: Write operation complete with <Write(1, 7, 2)>, sending <WriteFinished()> to 1.<br>" 
+ "1: Acknowledge/writeFinished answer <WriteFinished()> received from 1.<br>" 
+ "1: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "1: Get operation complete. Returning <k, v, t : (1, 7, 2)>.<br>" 
+ "1: Starting put operation (curr_iter: 5, curr_op: 5, until: 6).<br>" 
+ "1: Sending write acknowledgement requests.<br>" 
+ "3: Write operation complete with <Write(1, 7, 3)>, sending <WriteFinished()> to 3.<br>" 
+ "1: Acknowledge/write request <WriteAckReq(1, 13, 5)> received from 1. Sending <WriteAck(1, 13, 3, 5)> to 1.<br>" 
+ "3: Write operation <Write(1, 7, 2)> received from 1.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "1: Acknowledge/put answer received from 1. Received <WriteAck(1, 13, 3, 5)><br>" 
+ "3: Write operation complete with <Write(1, 7, 2)>, sending <WriteFinished()> to 1.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 1.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Put operation complete with (k = 1, v = 7); new timestamp: 3.<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 13, 5)> received from 1. Sending <WriteAck(1, 13, 3, 5)> to 1.<br>" 
+ "3: Starting get operation (curr_iter: 4, curr_op: 4, until: 6).<br>" 
+ "3: Sending read acknowledgement requests.<br>" 
+ "3: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 7, 3, 4)> to 3.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 7, 3, 4)> received from 3.<br>" 
+ "1: Acknowledge/put answer received from 3. Received <WriteAck(1, 13, 3, 5)><br>" 
+ "1: PUT : Got answers from a majority of actors. Continuing put operation <1, 13, 4>.<br>" 
+ "1: Got coherent maximum timestamp. Continuing put operation <1, 13, 4>.<br>" 
+ "3: Write operation <Write(1, 13, 4)> received from 1.<br>" 
+ "3: Write operation complete with <Write(1, 13, 4)>, sending <WriteFinished()> to 1.<br>" 
+ "1: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 7, 3, 4)> to 3.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 7, 3, 4)> received from 1.<br>" 
+ "3: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 7, 3)>.<br>" 
+ "3: Write operation <Write(1, 7, 4)> received from 3.<br>" 
+ "3: Write operation complete with <Write(1, 7, 4)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 7, 4)>.<br>" 
+ "3: Starting put operation (curr_iter: 5, curr_op: 5, until: 6).<br>" 
+ "3: Sending write acknowledgement requests.<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 13, 5)> received from 3. Sending <WriteAck(1, 13, 4, 5)> to 3.<br>" 
+ "3: Acknowledge/put answer received from 3. Received <WriteAck(1, 13, 4, 5)><br>" 
+ "1: Write operation <Write(1, 13, 4)> received from 1.<br>" 
+ "1: Write operation complete with <Write(1, 13, 4)>, sending <WriteFinished()> to 1.<br>" 
+ "1: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "1: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "1: Put operation complete with (k = 1, v = 13); new timestamp: 4.<br>" 
+ "1: Write operation <Write(1, 7, 4)> received from 3.<br>" 
+ "1: Write operation complete with <Write(1, 7, 4)>, sending <WriteFinished()> to 3.<br>" 
+ "1: Acknowledge/write request <WriteAckReq(1, 13, 5)> received from 3. Sending <WriteAck(1, 13, 4, 5)> to 3.<br>" 
+ "3: Acknowledge/put answer received from 1. Received <WriteAck(1, 13, 4, 5)><br>" 
+ "3: PUT : Got answers from a majority of actors. Continuing put operation <1, 13, 5>.<br>" 
+ "3: Got coherent maximum timestamp. Continuing put operation <1, 13, 5>.<br>" 
+ "3: Write operation <Write(1, 13, 5)> received from 3.<br>" 
+ "3: Write operation complete with <Write(1, 13, 5)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Put operation complete with (k = 1, v = 13); new timestamp: 5.<br>" 
+ "1: Starting get operation (curr_iter: 6, curr_op: 6, until: 6).<br>" 
+ "1: Sending read acknowledgement requests.<br>" 
+ "3: Starting get operation (curr_iter: 6, curr_op: 6, until: 6).<br>" 
+ "3: Sending read acknowledgement requests.<br>" 
+ "1: Write operation <Write(1, 13, 5)> received from 3.<br>" 
+ "1: Write operation complete with <Write(1, 13, 5)>, sending <WriteFinished()> to 3.<br>" 
+ "1: Acknowledge/get request received from 1 for key 1. Sending <ReadAck(1, 13, 5, 6)> to 1.<br>" 
+ "3: Acknowledge/get request received from 1 for key 1. Sending <ReadAck(1, 13, 5, 6)> to 1.<br>" 
+ "3: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 13, 5, 6)> to 3.<br>" 
+ "1: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 13, 5, 6)> to 3.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 13, 5, 6)> received from 1.<br>" 
+ "1: Acknowledge/get answer <ReadAck(1, 13, 5, 6)> received from 1.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 13, 5, 6)> received from 3.<br>" 
+ "3: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "1: Acknowledge/get answer <ReadAck(1, 13, 5, 6)> received from 3.<br>" 
+ "1: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "1: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 13, 5)>.<br>" 
+ "1: Get operation complete. Returning <k, v, t : (1, 13, 5)>.<br>" 
+ "3: Write operation <Write(1, 13, 5)> received from 3.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "3: Write operation complete with <Write(1, 13, 5)>, sending <WriteFinished()> to 3.<br>" 
+ "1: Write operation <Write(1, 13, 5)> received from 3.<br>" 
+ "1: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "1: Write operation complete with <Write(1, 13, 5)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Write operation <Write(1, 13, 5)> received from 1.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "1: Write operation <Write(1, 13, 5)> received from 1.<br>" 
+ "1: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "1: Write operation complete with <Write(1, 13, 5)>, sending <WriteFinished()> to 1.<br>" 
+ "3: Write operation complete with <Write(1, 13, 5)>, sending <WriteFinished()> to 1.<br>" 
+ "1: Acknowledge/writeFinished answer <WriteFinished()> received from 1.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "1: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "1: Get operation complete. Returning <k, v, t : (1, 13, 5)>.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "1: Time to die. Execution time: 19ms.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 13, 5)>.<br>" 
+ "3: Time to die. Execution time: 19ms.<br>" 
+ "main: Let the gates of death open.<br>" 
+ "main: Goodbye Universe.<br>" 
