var history_console = ""
+ "Slf4jLogger started<br>" 
+ "System started with N=3<br>" 
+ "Total System Runtime: 18ms.<br>" 
+ "Time performances:<br>" 
+ "2: faulty <=> system runtime (18ms)<br>" 
+ "1: 17ms<br>" 
+ "3: 12ms<br>" 
