var history_console = ""
+ "Slf4jLogger started<br>" 
+ "System started with N=3<br>" 
+ "1: Received other processes' info.<br>" 
+ "3: Received other processes' info.<br>" 
+ "2: Received other processes' info.<br>" 
+ "main: Received other processes' info.<br>" 
+ "1: Becoming faulty.<br>" 
+ "2: Launching. Starting sequential puts (followed by sequential gets).<br>" 
+ "2: Starting put operation (curr_iter: 1, curr_op: 1, until: 6).<br>" 
+ "2: Sending write acknowledgement requests.<br>" 
+ "2: Acknowledge/write request <WriteAckReq(1, 1, 1)> received from 2. Sending <WriteAck(1, 1, 0, 1)> to 2.<br>" 
+ "2: Acknowledge/put answer received from 2. Received <WriteAck(1, 1, 0, 1)><br>" 
+ "3: Launching. Starting sequential puts (followed by sequential gets).<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 1, 1)> received from 2. Sending <WriteAck(1, 1, 0, 1)> to 2.<br>" 
+ "2: Acknowledge/put answer received from 3. Received <WriteAck(1, 1, 0, 1)><br>" 
+ "2: PUT : Got answers from a majority of actors. Continuing put operation <1, 1, 1>.<br>" 
+ "2: Got coherent maximum timestamp. Continuing put operation <1, 1, 1>.<br>" 
+ "2: Write operation <Write(1, 1, 1)> received from 2.<br>" 
+ "2: Write operation complete with <Write(1, 1, 1)>, sending <WriteFinished()> to 2.<br>" 
+ "2: Acknowledge/writeFinished answer <WriteFinished()> received from 2.<br>" 
+ "2: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "2: Put operation complete with (k = 1, v = 1); new timestamp: 1.<br>" 
+ "2: Starting get operation (curr_iter: 2, curr_op: 2, until: 6).<br>" 
+ "2: Sending read acknowledgement requests.<br>" 
+ "2: Acknowledge/get request received from 2 for key 1. Sending <ReadAck(1, 1, 1, 2)> to 2.<br>" 
+ "2: Acknowledge/get answer <ReadAck(1, 1, 1, 2)> received from 2.<br>" 
+ "3: Starting put operation (curr_iter: 1, curr_op: 1, until: 6).<br>" 
+ "3: Sending write acknowledgement requests.<br>" 
+ "2: Acknowledge/write request <WriteAckReq(1, 2, 1)> received from 3. Sending <WriteAck(1, 2, 1, 1)> to 3.<br>" 
+ "3: Write operation <Write(1, 1, 1)> received from 2.<br>" 
+ "3: Write operation complete with <Write(1, 1, 1)>, sending <WriteFinished()> to 2.<br>" 
+ "3: Acknowledge/get request received from 2 for key 1. Sending <ReadAck(1, 1, 1, 2)> to 2.<br>" 
+ "2: Acknowledge/get answer <ReadAck(1, 1, 1, 2)> received from 3.<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 2, 1)> received from 3. Sending <WriteAck(1, 2, 1, 1)> to 3.<br>" 
+ "3: Acknowledge/put answer received from 2. Received <WriteAck(1, 2, 1, 1)><br>" 
+ "3: Acknowledge/put answer received from 3. Received <WriteAck(1, 2, 1, 1)><br>" 
+ "3: PUT : Got answers from a majority of actors. Continuing put operation <1, 2, 2>.<br>" 
+ "3: Got coherent maximum timestamp. Continuing put operation <1, 2, 2>.<br>" 
+ "3: Write operation <Write(1, 2, 2)> received from 3.<br>" 
+ "3: Write operation complete with <Write(1, 2, 2)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Put operation complete with (k = 1, v = 2); new timestamp: 2.<br>" 
+ "3: Starting get operation (curr_iter: 2, curr_op: 2, until: 6).<br>" 
+ "3: Sending read acknowledgement requests.<br>" 
+ "3: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 2, 2, 2)> to 3.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 2, 2, 2)> received from 3.<br>" 
+ "2: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "2: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "2: Get operation complete. Returning <k, v, t : (1, 1, 1)>.<br>" 
+ "3: Write operation <Write(1, 1, 1)> received from 2.<br>" 
+ "2: Write operation <Write(1, 2, 2)> received from 3.<br>" 
+ "2: Write operation complete with <Write(1, 2, 2)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "3: Write operation complete with <Write(1, 1, 1)>, sending <WriteFinished()> to 2.<br>" 
+ "2: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 2, 2, 2)> to 3.<br>" 
+ "2: Write operation <Write(1, 1, 1)> received from 2.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 2, 2, 2)> received from 2.<br>" 
+ "2: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "3: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "2: Write operation complete with <Write(1, 1, 1)>, sending <WriteFinished()> to 2.<br>" 
+ "3: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "2: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 2, 2)>.<br>" 
+ "2: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Write operation <Write(1, 2, 2)> received from 3.<br>" 
+ "2: Get operation complete. Returning <k, v, t : (1, 2, 1)>.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "3: Write operation complete with <Write(1, 2, 2)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "2: Write operation <Write(1, 2, 2)> received from 3.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "2: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 2, 2)>.<br>" 
+ "2: Write operation complete with <Write(1, 2, 2)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Starting put operation (curr_iter: 3, curr_op: 3, until: 6).<br>" 
+ "2: Starting put operation (curr_iter: 3, curr_op: 3, until: 6).<br>" 
+ "3: Sending write acknowledgement requests.<br>" 
+ "2: Sending write acknowledgement requests.<br>" 
+ "2: Acknowledge/write request <WriteAckReq(1, 8, 3)> received from 3. Sending <WriteAck(1, 8, 2, 3)> to 3.<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 8, 3)> received from 2. Sending <WriteAck(1, 8, 2, 3)> to 2.<br>" 
+ "2: Acknowledge/write request <WriteAckReq(1, 8, 3)> received from 2. Sending <WriteAck(1, 8, 2, 3)> to 2.<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 8, 3)> received from 3. Sending <WriteAck(1, 8, 2, 3)> to 3.<br>" 
+ "2: Acknowledge/put answer received from 3. Received <WriteAck(1, 8, 2, 3)><br>" 
+ "3: Acknowledge/put answer received from 2. Received <WriteAck(1, 8, 2, 3)><br>" 
+ "2: Acknowledge/put answer received from 2. Received <WriteAck(1, 8, 2, 3)><br>" 
+ "2: PUT : Got answers from a majority of actors. Continuing put operation <1, 8, 3>.<br>" 
+ "3: Acknowledge/put answer received from 3. Received <WriteAck(1, 8, 2, 3)><br>" 
+ "2: Got coherent maximum timestamp. Continuing put operation <1, 8, 3>.<br>" 
+ "3: PUT : Got answers from a majority of actors. Continuing put operation <1, 8, 3>.<br>" 
+ "3: Got coherent maximum timestamp. Continuing put operation <1, 8, 3>.<br>" 
+ "2: Write operation <Write(1, 8, 3)> received from 2.<br>" 
+ "3: Write operation <Write(1, 8, 3)> received from 2.<br>" 
+ "2: Write operation complete with <Write(1, 8, 3)>, sending <WriteFinished()> to 2.<br>" 
+ "3: Write operation complete with <Write(1, 8, 3)>, sending <WriteFinished()> to 2.<br>" 
+ "2: Write operation <Write(1, 8, 3)> received from 3.<br>" 
+ "2: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "2: Write operation complete with <Write(1, 8, 3)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Write operation <Write(1, 8, 3)> received from 3.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "3: Write operation complete with <Write(1, 8, 3)>, sending <WriteFinished()> to 3.<br>" 
+ "2: Acknowledge/writeFinished answer <WriteFinished()> received from 2.<br>" 
+ "2: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "2: Put operation complete with (k = 1, v = 8); new timestamp: 3.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 2.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Put operation complete with (k = 1, v = 8); new timestamp: 3.<br>" 
+ "2: Starting get operation (curr_iter: 4, curr_op: 4, until: 6).<br>" 
+ "3: Starting get operation (curr_iter: 4, curr_op: 4, until: 6).<br>" 
+ "2: Sending read acknowledgement requests.<br>" 
+ "3: Sending read acknowledgement requests.<br>" 
+ "2: Acknowledge/get request received from 2 for key 1. Sending <ReadAck(1, 8, 3, 4)> to 2.<br>" 
+ "3: Acknowledge/get request received from 2 for key 1. Sending <ReadAck(1, 8, 3, 4)> to 2.<br>" 
+ "2: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 8, 3, 4)> to 3.<br>" 
+ "3: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 8, 3, 4)> to 3.<br>" 
+ "2: Acknowledge/get answer <ReadAck(1, 8, 3, 4)> received from 2.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 8, 3, 4)> received from 2.<br>" 
+ "2: Acknowledge/get answer <ReadAck(1, 8, 3, 4)> received from 3.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 8, 3, 4)> received from 3.<br>" 
+ "2: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "2: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "3: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 8, 3)>.<br>" 
+ "3: Write operation <Write(1, 8, 3)> received from 3.<br>" 
+ "2: Get operation complete. Returning <k, v, t : (1, 8, 3)>.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "2: Write operation <Write(1, 8, 3)> received from 2.<br>" 
+ "3: Write operation complete with <Write(1, 8, 3)>, sending <WriteFinished()> to 3.<br>" 
+ "2: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "2: Write operation complete with <Write(1, 8, 3)>, sending <WriteFinished()> to 2.<br>" 
+ "3: Write operation <Write(1, 8, 3)> received from 2.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "2: Write operation <Write(1, 8, 3)> received from 3.<br>" 
+ "3: Write operation complete with <Write(1, 8, 3)>, sending <WriteFinished()> to 2.<br>" 
+ "2: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "2: Write operation complete with <Write(1, 8, 3)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "2: Acknowledge/writeFinished answer <WriteFinished()> received from 2.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "2: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 8, 3)>.<br>" 
+ "2: Get operation complete. Returning <k, v, t : (1, 8, 3)>.<br>" 
+ "3: Starting put operation (curr_iter: 5, curr_op: 5, until: 6).<br>" 
+ "3: Sending write acknowledgement requests.<br>" 
+ "2: Starting put operation (curr_iter: 5, curr_op: 5, until: 6).<br>" 
+ "2: Sending write acknowledgement requests.<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 14, 5)> received from 3. Sending <WriteAck(1, 14, 3, 5)> to 3.<br>" 
+ "2: Acknowledge/write request <WriteAckReq(1, 14, 5)> received from 3. Sending <WriteAck(1, 14, 3, 5)> to 3.<br>" 
+ "3: Acknowledge/write request <WriteAckReq(1, 14, 5)> received from 2. Sending <WriteAck(1, 14, 3, 5)> to 2.<br>" 
+ "2: Acknowledge/write request <WriteAckReq(1, 14, 5)> received from 2. Sending <WriteAck(1, 14, 3, 5)> to 2.<br>" 
+ "3: Acknowledge/put answer received from 3. Received <WriteAck(1, 14, 3, 5)><br>" 
+ "2: Acknowledge/put answer received from 3. Received <WriteAck(1, 14, 3, 5)><br>" 
+ "3: Acknowledge/put answer received from 2. Received <WriteAck(1, 14, 3, 5)><br>" 
+ "2: Acknowledge/put answer received from 2. Received <WriteAck(1, 14, 3, 5)><br>" 
+ "3: PUT : Got answers from a majority of actors. Continuing put operation <1, 14, 4>.<br>" 
+ "2: PUT : Got answers from a majority of actors. Continuing put operation <1, 14, 4>.<br>" 
+ "3: Got coherent maximum timestamp. Continuing put operation <1, 14, 4>.<br>" 
+ "2: Got coherent maximum timestamp. Continuing put operation <1, 14, 4>.<br>" 
+ "3: Write operation <Write(1, 14, 4)> received from 2.<br>" 
+ "3: Write operation complete with <Write(1, 14, 4)>, sending <WriteFinished()> to 2.<br>" 
+ "2: Write operation <Write(1, 14, 4)> received from 3.<br>" 
+ "3: Write operation <Write(1, 14, 4)> received from 3.<br>" 
+ "2: Write operation complete with <Write(1, 14, 4)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "3: Write operation complete with <Write(1, 14, 4)>, sending <WriteFinished()> to 3.<br>" 
+ "2: Write operation <Write(1, 14, 4)> received from 2.<br>" 
+ "2: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 2.<br>" 
+ "2: Write operation complete with <Write(1, 14, 4)>, sending <WriteFinished()> to 2.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Put operation complete with (k = 1, v = 14); new timestamp: 4.<br>" 
+ "2: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "2: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "2: Put operation complete with (k = 1, v = 14); new timestamp: 4.<br>" 
+ "3: Starting get operation (curr_iter: 6, curr_op: 6, until: 6).<br>" 
+ "3: Sending read acknowledgement requests.<br>" 
+ "2: Starting get operation (curr_iter: 6, curr_op: 6, until: 6).<br>" 
+ "2: Sending read acknowledgement requests.<br>" 
+ "3: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 14, 4, 6)> to 3.<br>" 
+ "2: Acknowledge/get request received from 3 for key 1. Sending <ReadAck(1, 14, 4, 6)> to 3.<br>" 
+ "3: Acknowledge/get request received from 2 for key 1. Sending <ReadAck(1, 14, 4, 6)> to 2.<br>" 
+ "2: Acknowledge/get request received from 2 for key 1. Sending <ReadAck(1, 14, 4, 6)> to 2.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 14, 4, 6)> received from 3.<br>" 
+ "2: Acknowledge/get answer <ReadAck(1, 14, 4, 6)> received from 3.<br>" 
+ "3: Acknowledge/get answer <ReadAck(1, 14, 4, 6)> received from 2.<br>" 
+ "3: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "2: Acknowledge/get answer <ReadAck(1, 14, 4, 6)> received from 2.<br>" 
+ "3: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "2: GET: Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "2: Got coherent maximum timestamp. Continuing get operation.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 14, 4)>.<br>" 
+ "2: Get operation complete. Returning <k, v, t : (1, 14, 4)>.<br>" 
+ "3: Write operation <Write(1, 14, 4)> received from 3.<br>" 
+ "2: Write operation <Write(1, 14, 4)> received from 3.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "2: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "3: Write operation complete with <Write(1, 14, 4)>, sending <WriteFinished()> to 3.<br>" 
+ "2: Write operation complete with <Write(1, 14, 4)>, sending <WriteFinished()> to 3.<br>" 
+ "3: Write operation <Write(1, 14, 4)> received from 2.<br>" 
+ "3: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "3: Write operation complete with <Write(1, 14, 4)>, sending <WriteFinished()> to 2.<br>" 
+ "2: Write operation <Write(1, 14, 4)> received from 2.<br>" 
+ "2: Write operation non-effective because of lower timestamp/higher value.<br>" 
+ "2: Write operation complete with <Write(1, 14, 4)>, sending <WriteFinished()> to 2.<br>" 
+ "3: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "3: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Get operation complete. Returning <k, v, t : (1, 14, 4)>.<br>" 
+ "2: Acknowledge/writeFinished answer <WriteFinished()> received from 3.<br>" 
+ "2: WRITE FINISHED : Got answers from a majority of actors. Quorum achieved, continuing.<br>" 
+ "3: Time to die. Execution time: 27ms.<br>" 
+ "2: Get operation complete. Returning <k, v, t : (1, 14, 4)>.<br>" 
+ "2: Time to die. Execution time: 27ms.<br>" 
+ "main: Sending Poison Pills.<br>" 
+ "main: Goodbye Universe.<br>" 
+ "main: Total System Runtime: 32ms.<br>" 
+ "main: Time performances:<br>" 
+ "main: 2: 27ms<br>" 
+ "main: 1: faulty <=> system runtime (32ms)<br>" 
+ "main: 3: 27ms<br>" 
